# Generated by Django 3.2.9 on 2021-11-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='product',
        ),
    ]
