# Generated by Django 3.2.9 on 2021-11-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productAdmin', '0004_auto_20211105_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='order entry date')),
                ('order_time', models.TimeField(auto_now_add=True, verbose_name='order entry time')),
                ('customer_name', models.CharField(max_length=72)),
                ('shipping_address', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productAdmin.product')),
            ],
        ),
    ]
