# Generated by Django 3.2.9 on 2021-11-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAdmin', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
